server:
  port: 8082
hm:
  db:
    database: hm-cart
  swagger:
    title: 购物车接口文档
    package: com.hmall.cart.controller
  cart:
    maxSize: 2 # 购物车购物

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel控制台地址
      http-method-specify: true # 开启请求方式前缀